name: Install Uptime Kuma on Ubuntu VM

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Target Ubuntu host (IP/hostname)"
        required: true
      user:
        description: "SSH user"
        default: "admino"
      ssh_key_path:
        description: "Private key path on self-hosted runner"
        default: "~/.ssh/github_runner_id"

jobs:
  install-uptime-kuma:
    runs-on: self-hosted
    steps:
      - name: Expand SSH key path
        run: |
          KEY_PATH="${{ github.event.inputs.ssh_key_path }}"
          KEY_PATH="${KEY_PATH/#\~/$HOME}"
          echo "SSH_KEY=$KEY_PATH" >> $GITHUB_ENV

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H "${{ github.event.inputs.server }}" >> ~/.ssh/known_hosts || true

      - name: Test SSH connectivity
        run: |
          ssh -i "$SSH_KEY" -o BatchMode=yes -o ConnectTimeout=5 \
            "${{ github.event.inputs.user }}"@"${{ github.event.inputs.server }}" \
            "echo '✅ SSH Connected'"

      - name: Install Uptime Kuma
        run: |
          ssh -i "$SSH_KEY" "${{ github.event.inputs.user }}"@"${{ github.event.inputs.server }}" <<'EOF'
            set -e
            # install dependencies
            sudo apt-get update -y
            sudo apt-get install -y git curl build-essential

            # install Node.js LTS
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # clone uptime-kuma
            if [ ! -d "/home/${USER}/uptime-kuma" ]; then
              git clone https://github.com/louislam/uptime-kuma.git /home/${USER}/uptime-kuma
            fi

            cd /home/${USER}/uptime-kuma
            npm install --production

            # setup systemd service
            sudo tee /etc/systemd/system/uptime-kuma.service > /dev/null <<SERVICE
            [Unit]
            Description=Uptime Kuma
            After=network.target

            [Service]
            Type=simple
            User=${USER}
            WorkingDirectory=/home/${USER}/uptime-kuma
            ExecStart=/usr/bin/npm start
            Restart=always
            RestartSec=10

            [Install]
            WantedBy=multi-user.target
            SERVICE

            sudo systemctl daemon-reexec
            sudo systemctl enable uptime-kuma
            sudo systemctl restart uptime-kuma
          EOF

      - name: Confirm service status
        run: |
          ssh -i "$SSH_KEY" "${{ github.event.inputs.user }}"@"${{ github.event.inputs.server }}" \
            "systemctl is-active uptime-kuma && echo '🎉 Uptime Kuma installed & running'"
